### ISSUE TITLE
Since v2.1.0, cannot join servers without host having mod installed

### ISSUE THREAD

**Issue by Nuzza** [cmooref17/Lethal-Company-TooManyEmotes#107]
Since version 2.1.0, joining servers that don't have TooManyEmotes is no longer possible.

Is it possible to have either an option to disable the new grabbable items to bring back client side only or perhaps a separate mod without the grabbable items?

**Comment by cmooref17** [comment]
Oh shoot. I didn't even think about this. I will have to think up a solution to this soon.
It's likely causing issues because the grabbable props have to be added into the list of network prefabs in the main menu, so the game realizes there's a mismatch there. If I could add the props after a player joins, I would, but that also causes issues.

I could either make a separate mod that adds in those emote props as scrap, or add a config that allows players to force disable emote props, even as a non-host client, and add warnings that enabling props would prevent them from joining players without the mod, and from joining players with the props disabled.

Thanks for letting me know about this. I'll try to get a solution pushed for this soon when I have time!
