### ISSUE TITLE
[Bug] scan node locations bug while emoting

### ISSUE THREAD

**Issue by ajsglist** [cmooref17/Lethal-Company-TooManyEmotes#130]
hey there,

just noticed that the scan nodes on the ship are moving while emoting.  Seems to be shifting positions when the first person camera position moves (despite the actual third person cam being stationary)

![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/139426529/c70d4186-27fa-42d0-a1dc-63f37d51d572)

**Comment by ajsglist** [comment]
Hey there,

Just for clarity since this bug is still present, this occurs with all scan nodes.  It's incredibly disorienting/annoying, so it would be great if this could be investigated when you have time.

Thanks again

**Comment by cmooref17** [comment]
Do you know for sure that this bug was not fixed previously? Or could it have been reintroduced when I made some slight changes to the rendering in the latest update?

I thought I had this part fixed already, so I was under the impression that I might have just broke that again.

Thanks and let me know! I can check on this tomorrow though.

**Comment by cmooref17** [comment]
Also, if I did fix this in the past, I apologize for not making any notes here.

**Comment by cmooref17** [comment]
Sorry, I thought I had this fixed in the past. I pushed an update out now, and it should be working now. (2.1.24)
If not, please let me know!

**Comment by ajsglist** [comment]
Nothing to apologize for.  A quick check with the new version seems to have fixed it.

Thanks for addressing this!
