### ISSUE TITLE
Only the host can see their own cosmetics in third person (More Company)

### ISSUE THREAD

**Issue by LilyArlatto** [cmooref17/Lethal-Company-TooManyEmotes#14]
I tested and apparently only the host can see their own cosmetics while emoting, but anyone who joins the host cannot see their own hats (other players can still see them)

**Comment by alexdth** [comment]
same issue for me

**Comment by alexdth** [comment]
and when you emote as host, you see other members with your own cosmetics during the time the emote is played

**Comment by cmooref17** [comment]
For anyone who sees their cosmetics on other players when they emote, I did have this issue, but it was actually because in my cosmetics menu, in the main menu, the enable cosmetics checkbox was turned off. Could this be your issue? Once I turned it on, I saw everyone else's cosmetics, and mine did not appear on them anymore.

I still need to fix the issue with the non-host clients not being able to see their own while they emote, though.

**Comment by alexdth** [comment]
Thanks for the information, it wasnt with myself but with my friend who was the host, and indeed it was turned off for him.
Only reamaining issue is only the host can see his own cosmetics, but its not an horrible issue you did an amzing job so far already, just wanted to let you know because more comapny is one of the most downloaded mod

**Comment by LilyArlatto** [comment]
..Okay, maybe I didn't explain the issue thoroughly enough, my bad. 

The problem is that when you use an emote (and it puts you in third person), you can only see your own cosmetics _if you are the host._ I specifically tested this by booting up my own lobby and doing an emote, I could see my hats just fine. When I joined a friend, however, my hats were invisible for me whenever I used an emote, but they could see my hats on their screen and they could see their own hats during an emote just fine.

**Comment by cmooref17** [comment]
I believe this has finally been fixed, btw. If not, please reopen this ticket!

**Comment by alexdth** [comment]
well done!
