### ISSUE TITLE
[Bug] Favorites are broken 2.2.12

### ISSUE THREAD

**Issue by ajsglist** [cmooref17/Lethal-Company-TooManyEmotes#171]
Hey there,

The current version of TME has broken favorites.  It seems to correctly remember what was marked as favorite, but the "favorites" section is empty

![image](https://github.com/user-attachments/assets/b61d9ece-6244-44a4-8021-93d793e161e7)
![image](https://github.com/user-attachments/assets/8bdb00bd-0ce0-4800-a846-955a44d3e332)

**Comment by ajsglist** [comment]
New save files are also being created with 0 emote credits.

![image](https://github.com/user-attachments/assets/ae32f5d9-1e49-4227-b18d-d3c832c18cc7)
![image](https://github.com/user-attachments/assets/737cd0df-a343-4961-a589-24aca56db140)

**Comment by cmooref17** [comment]
Oh, thanks for letting me know! I will try to look at this tomorrow, or as soon as possible. I must have broken something then

**Comment by cmooref17** [comment]
I believe I got this fixed in 2.2.13
Could you let me know if this is resolved when you get the chance?

Originally, I made it so the game wouldn't save/load if you had all emotes unlocked in the config, but I accidentally had it reversed so it wouldn't save/load if you did enable unlocking emotes. Whoops!

**Comment by ajsglist** [comment]
favorites and starting credits are back in 2.2.13 👍
