### ISSUE TITLE
Only 1 page of emotes?

### ISSUE THREAD

**Issue by BitTripBoy** [cmooref17/Lethal-Company-TooManyEmotes#4]
This emote mod was working last night, and then today it only has one page out of the total 13. The weird thing is that I sometimes open it and it works, and other times it doesn't.

The code: 018cd809-c607-0a50-ad76-cf2a2beffe1e

**Comment by cmooref17** [comment]
Did you somehow reset your config in TooManyEmotes? I believe copying a code should copy the configs as well, and it looks like with your code, you have the I am a Party Pooper mode disabled, meaning you start off with the complementary emotes, and have to purchase the rest of them. (btw, I don't think anyone's a party pooper uses uses this option :) )

If you had all emotes unlocked without touching this setting, it could have been due to a bug I fixed a couple days ago? I think?
Let me know if this helps.
