### ISSUE TITLE
Ghost girl visable to all players while in 3rd person emoting.

### ISSUE THREAD

**Issue by AGuyNamedSparre** [cmooref17/Lethal-Company-TooManyEmotes#5]
Emoting allows everyone to see the ghost girl, including after she "walks through a wall" or "disappears" around a corner.

Example Video: 
https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/14899002/5b194254-4c99-468f-b10e-b0c0a551a993

**Comment by cmooref17** [comment]
This one is a difficult one, because of how other popular mods handle viewing certain objects on the Enemies Not Rendered layer. My third person camera does the same to help with compatibility. When running MoreCompany cosmetics, the third person camera views this layer so it can see the cosmetics while you emote, but the main camera cannot see them. With the mirror decor mod, the camera that renders your player can see the cosmetics, which is why you see them in the mirror. This is also how the popular third-person camera mods work. I could possibly change some things specifically for this, and maybe make it so that the third person emote camera cannot view this layer when inside the building, but I'd have to find a solution to display the MoreCompany cosmetics again.

Hope this makes sense, but currently, it just has to be this way until I have time to work on this. I have some updates planned first, but thanks for this comment!
