### ISSUE TITLE
[Idea] Add music to some of the emotes

### ISSUE THREAD

**Issue by Skubers** [cmooref17/Lethal-Company-TooManyEmotes#6]
As the title suggests, adding a looping music to the emotes would be a really nice social touch

**Comment by cmooref17** [comment]
Technically, I already have the code for this in the mod. It works by checking if there is a boombox nearby, and if the emote you're playing has a song with the same name in one of the asset bundles, it will attempt to play that song, and it seems to work fine.

However, I am a little cautious about adding songs that could flag my mod with anything copyright related, so I currently don't have any songs added into my mod. After I finish some planned updates, maybe I'll get around to compiling an asset bundle of songs that will work for this mod, and provide them as a download from another source instead of including them in my mod, and you would just drag and drop the asset bundle into the mod's asset bundle folder, and ideally, it would just "work" with how my code is set up.

I would say keep your eyes peeled for any information about this on the mod page on the thunderstore in case I do this soon!
