### ISSUE TITLE
Certain emotes appearing as default dance

### ISSUE THREAD

**Issue by AustinStin** [cmooref17/Lethal-Company-TooManyEmotes#64]
When joining a lobby with 3 other people who have the mod, certain dances appear as the normal Lethal Company default dance to some. This varies person to person on who can see it or not aswell. Confirming we are all on the same version had no results either.

**Comment by cmooref17** [comment]
Does it ever appear as the normal emote for yourself? Or does it only do it sometimes for other people?

**Comment by AustinStin** [comment]
Exclusively other players, the person using them has been able to see them each time we have tried. In multiple playthroughs only a handful of the emotes had this happen and it's seemingly random per person which ones won't appear. (I can see Spiderman, two cannot while one other can for example.)

**Comment by BubblyBall** [comment]
I get the same issue with my friends. I can see just fine the emotes I do, but one of my friends do not see the emote and just sees the default dance or point, and another friend of mine sees the emotes just fine. We all have done the same install process and we have a newest version. No idea what's going on.

**Comment by cmooref17** [comment]
Sorry for asking way late, but has any of my recent updates fixed this issue? I'm bad at checking my issues sometimes.

**Comment by fbgranell** [comment]
A friend of mine has the same issue @BubblyBall explained. She had the mod and it worked fine until some days ago she couldn't see the emote wheel anymore, and when we emote she doesn't see the real animation/songs, she just sees the default game dance. We tried reinstalling the game, reinstalling r2modman, deleting Appdata files, reinstalling the mods, even disabling all mods except toomanyemotes, but it won't work. We're confused because even after deleting all the files and reinstalling, the shortcut for the emote wheel is saved (so I guess some files were not deleted).

**Comment by cmooref17** [comment]
Those are saved with the ES3 system. (Easy save?) I'm not too sure how or where those are stored, to be honest.

And does it play the default dance for every emote? Does anyone get errors in the console when this bug happens?

Also, I'm pushing an update out soon, and will include a config option to force reset favorited emotes the next time you start up the game. This might fix some issues, but it's hard to tell what's going on exactly.

**Comment by fbgranell** [comment]
We get no errors in the console when emoting, and she doesn't either. We do see the normal receiving emote lines in the console, but she doesn't. We just updated to the latest version but her emote wheel keybind still doesn't work (she tried different keys), and she still can't see our emotes either. Any idea what can we do to fix it? We're confused because reinstalling everything didn't work

**Comment by cmooref17** [comment]
If you guys have the chance, could you try downloading the latest version? And then go into your config, and choose to force reset the favorited emotes? I am curious on if this will fix your issue.

**Comment by fbgranell** [comment]
We just downloaded the latest version, and tried the force reset. It did change her wheel keybind to the default one, but the wheel still doesn't show when she presses the key. We also tried several emotes, the violin one, and several dances and all she sees is the default dance. We also tried disabling all the other mods to see if it was a compatibility issue, but it won't work even as the only mod. Are the console errors logged into any file? So we can easily search for errors related to this particular mod?

**Comment by cmooref17** [comment]
You can find the log in your profile/MyProfile/BepInEx folder.
This is what the path for mine is:
C:\Users\MY_USER\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Flip\BepInEx

But if you're not using r2modman, you might have to find where your log file is yourself.

And this is only a problem with her? Do you know for sure that the mod is actually loading for her? I had a very strange case one time where I couldn't play with my friends because a specific mod was being stubborn, and everytime I downloaded/updated it, it would not download the .dll. I finally fixed this by deleting my mod cache folder.
The path to it for me was:
C:\Users\MY_USER\AppData\Roaming\r2modmanPlus-local\LethalCompany\cache

Or you can find this in r2modman by clicking Settings>Browse Data Folder, and then in the folder that opens, go to Lethal Company, and delete the cache folder.

When I deleted the cache folder, and after redownloading that mod, it started working. This might not even work for her, but I would recommend trying this.

**Comment by fbgranell** [comment]
Thanks for the help. We found the log and it starts loading the mod but it seems to stop after an error because she doesn't get the _[Info   :TooManyEmotes-2.0.8] TooManyEmotes loaded_ line that we see in our consoles. Her log is this one:
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/111991424/8513f4b8-6bd5-469c-a898-df874b3f0151)

And yes, she's the only one of us having the problem (but it used to work for her too like a week ago). We tried removing the cache folder and every folder from appdata before reinstalling r2modman, reinstalling the game, etc, but none of those work.

**Comment by cmooref17** [comment]
I'm not too sure about the cryptographicexception. It sounds like an error with the ES3 saving system that the game uses. I tried looking into this, and someone suggested to try deleting some possible corrupt saves.

Maybe you could try going to this folder and deleting (or backing up) theses files in this directory, and see if this fixes anything.
C:\Users\YOUR_USER_FOLDER\AppData\LocalLow\ZeekerssRBLX\Lethal Company

Someone said doing this made that error go away. Hopefully if that error goes away, it also fixes her issue. :/

**Comment by fbgranell** [comment]
We tried deleting the LocalLow\ZeekerssRBLX\Lethal Company folder today as you said and it worked, now everything runs fine for her, she's able to use emotes and see them. Thanks a lot for your help man 😄

**Comment by cmooref17** [comment]
Wow, normally those kind of fixes don't do anything for me haha. I'm glad it's working fine now!
